### PR TITLE
*important - working with community should follow the standard

### PR DESCRIPTION
**Pull request by metallurgical**
This changes does not change the way of the flow behave, rather formatting the code.  Please take a look of the changes.

Every single push to repo, can format the code with `composer format`

### CODE REVIEW

**Comment by hanisirfan** [comment]
What you meant by 
> Every single push to repo, can format the code with `composer format`

Sorry, I'm new in these thing.

**Comment by metallurgical** [comment]
Before push to repository, run "composer format" in your local CLI. The script will auto formatting the files (files you currently works on). 

Or you can configure your IDE to auto call `composer format` command whenever you saved the files. The former works better for me.

**Comment by hanisirfan** [comment]
Alright, thanks for the explanation. Maybe later I'll add the `composer format` into the Contribution guidelines.

Thanks a lot for the contribution.

**Comment by hanisirfan** [comment]
@all-contributors add @metallurgical for code

**Comment by metallurgical** [comment]
Thanks, create any issue/features, i'm happy to help in my free time :)

**Comment by hanisirfan** [comment]
@metallurgical No problem. Currently working on mail feature. Did you have a Discord account? I think it's better for us to chat there.

**Comment by metallurgical** [comment]
Yup boleh, ni username `metallurgical#3931`

**Comment by hanisirfan** [comment]
Nice. Requested.

**Pull request merged**
